#!/usr/bin/env python3
"""Pre-pass of the software-craft review: no LLM, standard library only.

Reads `git diff -U0 <diff_ref> [path_filter]` over text files — or, without a
diff_ref, the working tree against HEAD, staged, unstaged and untracked, since the
developer agent's diff is uncommitted — skips vendored, generated, minified, lock,
binary and unknown-language files by a documented deny-list, detects the language of
each file by extension, computes a fixed list of language-neutral structural signals
per hunk, matches every card's triggers (regular expressions against added lines, or
`signal:<name>`) and writes `craft/plan.json` plus `craft/plan.log` in the repository
under review. Nothing else is written; no network is opened.

plan.json carries:
  inventory     mode (committed | worktree), base_sha, head_sha or "worktree", changed
                files with language, kind and hunks (added lines with line numbers and
                the signals computed per hunk), skipped files with the reason, size
                class, config state
  cards         the index of the dispatched cards: rule_id, path, title, domain, step,
                applies_to, triggers, scope, check_kind, severity_default
  jobs          one per (card x slice): the files whose added lines matched the card's
                patterns or whose hunks carry its signal, with the matching hunks only
  slices        three to eight file groups for the always-on logic pass
  candidates    mechanical hits named outright, tagged needs_verification
  project_cards PROJ-N cards parsed from config.md, plus project card files

Usage:
  python3 static-craft.py --cards-dir <dir> [--diff-ref <base...head | a..b | commit>]
         [--path-filter <subtree>] [--repo <root>] [--out-dir craft]
         [--max-job-lines 400] [--max-jobs 96] [--config .claude/software-craft/config.md]
Exit status: 0 with a plan; 2 when the diff holds no reviewable change (an empty plan
is still written, so the caller can tell "nothing to review" from a crash).
"""
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from cardlib import read_card, is_signal, signal_name, SIGNALS  # noqa: E402

DEFAULT_CONFIG = os.path.join(".claude", "software-craft", "config.md")
PROJECT_CARDS_DIR = os.path.join(".claude", "software-craft", "cards")
SIZE_SMALL_MAX, SIZE_MEDIUM_MAX = 19, 49
MIN_SLICES, MAX_SLICES = 3, 8

# ---- language detection and the deny-list ---------------------------------------------------
LANGUAGES = {
    ".java": "java", ".py": "python", ".pyi": "python", ".ts": "typescript", ".tsx": "typescript",
    ".js": "javascript", ".jsx": "javascript", ".mjs": "javascript", ".cjs": "javascript",
    ".go": "go", ".rs": "rust", ".kt": "kotlin", ".kts": "kotlin", ".cs": "csharp",
    ".c": "c", ".h": "c", ".cc": "cpp", ".cpp": "cpp", ".hpp": "cpp", ".hh": "cpp",
    ".rb": "ruby", ".php": "php", ".swift": "swift", ".scala": "scala", ".groovy": "groovy",
    ".sh": "shell", ".bash": "shell", ".zsh": "shell", ".sql": "sql", ".proto": "proto",
    ".md": "markdown", ".rst": "markdown", ".txt": "text",
    ".yml": "yaml", ".yaml": "yaml", ".json": "json", ".toml": "toml", ".ini": "ini", ".cfg": "ini",
    ".xml": "xml", ".html": "html", ".css": "css", ".tf": "hcl", ".gradle": "groovy",
}
BRACE_LANGUAGES = {"java", "typescript", "javascript", "go", "rust", "kotlin", "csharp", "c", "cpp", "swift", "scala", "groovy", "php"}
INDENT_LANGUAGES = {"python"}
BUILD_NAMES = {"Dockerfile", "Makefile", "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle",
               "settings.gradle.kts", "package.json", "Cargo.toml", "go.mod", "pyproject.toml", "setup.py",
               "setup.cfg", "tsconfig.json", "requirements.txt", "CMakeLists.txt", "Gemfile", "composer.json"}
CONFIG_LANGUAGES = {"yaml", "json", "toml", "ini", "hcl", "xml"}
DOC_LANGUAGES = {"markdown", "text"}
VENDORED_DIRS = ("vendor/", "node_modules/", "third_party/", "third-party/", ".venv/", "venv/", "target/", "build/", "dist/", "out/", ".git/")
LOCK_FILES = {"package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Cargo.lock", "poetry.lock", "Pipfile.lock",
              "go.sum", "composer.lock", "Gemfile.lock", "flake.lock", "bun.lockb"}
GENERATED_NAME = re.compile(r"(_pb2\.py|_pb2_grpc\.py|\.pb\.go|_generated\.\w+|\.generated\.\w+|\.g\.\w+|\.min\.(js|css))$")
GENERATED_MARK = re.compile(r"(?i)\b(?:@generated|code generated|do not edit|autogenerated|auto-generated|generated by)\b")
MINIFIED_AVG_LINE = 400
TEST_PATH = re.compile(r"(?:^|/)(?:test|tests|__tests__|spec|specs|testing)/|(?:^|/)test_[^/]+\.py$|_test\.(?:py|go|rs|ts|js)$|"
                       r"Tests?\.(?:java|kt|cs|scala)$|\.(?:test|spec)\.(?:ts|tsx|js|jsx|mjs)$|_spec\.rb$")


def language_of(path):
    name = os.path.basename(path)
    if name in BUILD_NAMES:
        return LANGUAGES.get(os.path.splitext(name)[1].lower(), "build")
    return LANGUAGES.get(os.path.splitext(name)[1].lower())


def kind_of(path, language):
    name = os.path.basename(path)
    if name in BUILD_NAMES or language == "build":
        return "build"
    if TEST_PATH.search(path):
        return "test"
    if language in CONFIG_LANGUAGES:
        return "config"
    if language in DOC_LANGUAGES:
        return "docs"
    return "source"


def deny_reason(path, head_text):
    """The deny-list: the reason a file is skipped, or None."""
    name = os.path.basename(path)
    if any(seg in ("/" + path) for seg in ("/" + v for v in VENDORED_DIRS)):
        return "vendored"
    if name in LOCK_FILES:
        return "lock"
    if GENERATED_NAME.search(name):
        return "generated"
    if head_text is not None:
        head_lines = head_text.split("\n")
        if any(GENERATED_MARK.search(l) for l in head_lines[:5]):
            return "generated"
        long_lines = [l for l in head_lines if l.strip()]
        if long_lines and sum(len(l) for l in long_lines) / len(long_lines) > MINIFIED_AVG_LINE:
            return "minified"
    if language_of(path) is None:
        return "unknown-language"
    return None


# ---- git and the diff -------------------------------------------------------------------------
class Log:
    def __init__(self):
        self.lines = []

    def __call__(self, msg):
        self.lines.append(msg)


def die(msg):
    sys.exit(f"static-craft: {msg}")


def git(repo, *args, ok_codes=(0,)):
    out = subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True, errors="replace")
    if out.returncode not in ok_codes:
        die(f"git {' '.join(args)} failed: {out.stderr.strip()}")
    return out.stdout


def resolve_refs(repo, diff_ref):
    """Return (base_sha, head_sha) for the three accepted forms."""
    if "..." in diff_ref:
        a, b = diff_ref.split("...", 1)
        b = b or "HEAD"
        base = git(repo, "merge-base", a, b).strip()
        head = git(repo, "rev-parse", b).strip()
    elif ".." in diff_ref:
        a, b = diff_ref.split("..", 1)
        b = b or "HEAD"
        base = git(repo, "rev-parse", a).strip()
        head = git(repo, "rev-parse", b).strip()
    else:
        head = git(repo, "rev-parse", diff_ref).strip()
        base = git(repo, "rev-parse", f"{diff_ref}~1").strip()
    return base, head


HUNK = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")


def parse_diff(text):
    """Parse `git diff -U0` output into file records with added-line hunks; a binary file
    is recorded with binary=True and no hunks."""
    files, cur, hunk, new_no = [], None, None, 0
    for raw in text.split("\n"):
        if raw.startswith("diff --git "):
            m = re.match(r"diff --git a/(.*) b/(.*)$", raw)
            cur = {"path": m.group(2) if m else raw[11:], "status": "modified", "hunks": [],
                   "added_lines": 0, "removed_lines": 0, "binary": False}
            files.append(cur)
            hunk = None
            continue
        if cur is None:
            continue
        if raw.startswith("new file mode"):
            cur["status"] = "added"
            continue
        if raw.startswith("deleted file mode"):
            cur["status"] = "deleted"
            continue
        if raw.startswith("rename from"):
            cur["status"] = "renamed"
            continue
        if raw.startswith("Binary files"):
            cur["binary"] = True
            continue
        if raw.startswith("+++ ") or raw.startswith("--- ") or raw.startswith("index "):
            continue
        hm = HUNK.match(raw)
        if hm:
            new_no = int(hm.group(3))
            hunk = {"start": new_no, "base_start": int(hm.group(1)), "lines": []}
            cur["hunks"].append(hunk)
            continue
        if hunk is None:
            continue
        if raw.startswith("+"):
            hunk["lines"].append({"no": new_no, "text": raw[1:]})
            cur["added_lines"] += 1
            new_no += 1
        elif raw.startswith("-"):
            cur["removed_lines"] += 1
    for f in files:
        f["hunks"] = [h for h in f["hunks"] if h["lines"]]
    return [f for f in files if f["status"] != "deleted"]


def untracked_records(repo, path_filter):
    """Untracked files as added-file records, one hunk holding the whole file."""
    out = []
    listing = git(repo, "ls-files", "--others", "--exclude-standard", "--", *( [path_filter] if path_filter else [] ))
    for rel in listing.split("\n"):
        rel = rel.strip()
        if not rel:
            continue
        full = os.path.join(repo, rel)
        try:
            with open(full, "rb") as handle:
                raw = handle.read()
        except OSError:
            continue
        if b"\0" in raw[:8000]:
            out.append({"path": rel, "status": "added", "hunks": [], "added_lines": 0, "removed_lines": 0, "binary": True})
            continue
        text = raw.decode("utf-8", errors="replace")
        lines = text.split("\n")
        if lines and lines[-1] == "":
            lines = lines[:-1]
        out.append({"path": rel, "status": "added", "binary": False, "removed_lines": 0, "added_lines": len(lines),
                    "hunks": [{"start": 1, "base_start": 0, "lines": [{"no": i + 1, "text": l} for i, l in enumerate(lines)]}]})
    return out


def head_text(repo, mode, head_sha, path):
    if mode == "worktree":
        try:
            with open(os.path.join(repo, path), encoding="utf-8", errors="replace") as handle:
                return handle.read()
        except OSError:
            return None
    out = subprocess.run(["git", "-C", repo, "show", f"{head_sha}:{path}"], capture_output=True, text=True, errors="replace")
    return out.stdout if out.returncode == 0 else None


# ---- structural signals --------------------------------------------------------------------------
THRESHOLDS = {"long_routine": 40, "deep_nesting": 4, "many_parameters": 5}
CONTROL_KEYWORDS = re.compile(r"^\s*(?:if|else|elif|for|while|switch|match|do|try|catch|finally|return|throw|throws|new|case|default|"
                              r"synchronized|with|yield|await|import|package|using|namespace|struct|enum|interface|trait|impl|class|"
                              r"type|const|let|var|val|public|private|protected|static|final|abstract|override|export|module|"
                              r"loop|unsafe|defer|go|select|guard|repeat)\b(?!\s*\()")
SIGNATURE = re.compile(r"(?:^|[\s.])(?P<name>[A-Za-z_][\w$]*)\s*(?:<[^>()]*>)?\s*\((?P<rest>.*)$")
ARROW = re.compile(r"=>\s*\{\s*$")
STRING_LITERAL = re.compile(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|`(?:\\.|[^`\\])*`')
COMMENT_TAIL = re.compile(r"//.*$|/\*.*?\*/")
BOOL_ARG = re.compile(r"[A-Za-z_\]\)][\w$]*\s*\((?:[^()]*\([^()]*\))*[^()]*\b(?:true|false|True|False)\b")
BOOL_ARG_EXCLUDE = re.compile(r"^\s*(?:if|while|for|elif|else\s+if|switch|assert|return|@\w+|#\[|\.\.\.)")
MAGIC_NUMBER = re.compile(r"(?<![\w.])-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?(?:[fFdDlLuU]|_?[a-z]{1,3})?(?![\w.])")
MAGIC_ALLOWED = {"0", "1", "2", "-1", "100", "0.0", "1.0", "0.5", "2.0", "10", "-0"}
CONST_DECL = re.compile(r"^\s*(?:(?:public|private|protected|internal|export)\s+)?(?:static\s+final|final\s+static|const|static\s+let|readonly|val|"
                        r"static\s+readonly|const\s+val|enum|case)\b|^\s*[A-Z][A-Z0-9_]{2,}\s*[:=]|^\s*#define\b|^\s*@|^\s*#\[|^\s*(?:import|from|package|use)\b")
COMMENT_START = re.compile(r"^\s*(?://|#(?!\[)|\*|/\*|--|<!--)")
TODO = re.compile(r"\b(?:TODO|FIXME|HACK|XXX)\b")
STATEMENT_SYNTAX = re.compile(r";\s*$|[{}]|=|\b[A-Za-z_]\w*\(")
EMPTY_HANDLER_ONE_LINE = re.compile(r"\bcatch\b[^{]*\{\s*\}|\bexcept\b[^:]*:\s*(?:pass|\.\.\.)\s*(?:#.*)?$|\brescue\b[^\n]*\bend\b|"
                                    r"if\s+err\s*!=\s*nil\s*\{\s*\}|\b_\s*=\s*err\b|\.ok\(\)\s*;|let\s+_\s*=\s*\w+[^;]*\(")
EMPTY_HANDLER_OPEN = re.compile(r"\bcatch\b[^{]*\{\s*$|\bexcept\b[^:]*:\s*$|\brescue\b\s*(?:=>\s*\w+)?\s*$|if\s+err\s*!=\s*nil\s*\{\s*$|\.catch\(\s*(?:\(\s*\w*\s*\)|\w+)\s*=>\s*\{\s*$")
EMPTY_HANDLER_BODY = re.compile(r"^\s*(?:\}|pass|\.\.\.|return|end|\}\)\s*;?|//.*|#.*)\s*;?\s*$")
DUPLICATE_WINDOW = 6


def strip_literals(line):
    return COMMENT_TAIL.sub("", STRING_LITERAL.sub('""', line))


def is_signature(line, language):
    """A routine signature line: an identifier immediately before `(`, not a control keyword,
    on a line that opens a body (a brace at its end, an arrow body, a Python or Ruby def)."""
    s = strip_literals(line).rstrip()
    if not s.strip():
        return False
    if language in INDENT_LANGUAGES:
        return re.match(r"^\s*(?:async\s+)?def\s+\w+\s*\(", s) is not None
    if language == "ruby":
        return re.match(r"^\s*def\s+[\w.?!]+", s) is not None
    if CONTROL_KEYWORDS.match(s) and not re.match(r"^\s*(?:public|private|protected|static|final|abstract|override|export|async|const|let|var|val)\b", s):
        return False
    if re.match(r"^\s*(?:if|else|elif|for|while|switch|match|do|try|catch|finally|return|throw|new|case|synchronized|with|loop|defer|go|select|guard)\b", s):
        return False
    if re.match(r"^\s*(?:@|#\[)", s):
        return False
    if language == "go" and not re.match(r"^\s*func\b", s):
        return False
    if language == "rust" and not re.search(r"\bfn\s+\w+", s):
        return False
    if language == "kotlin" and not re.search(r"\bfun\s+", s) and "->" not in s:
        return False
    opens = s.endswith("{") or ARROW.search(s) is not None
    if not opens:
        # a signature whose brace or arrow sits on the next line, or Java/C# declarations
        # continued across lines: accept when the line ends inside the parameter list
        opens = s.count("(") > s.count(")")
    if not opens:
        return False
    m = SIGNATURE.search(s)
    if not m:
        return "=>" in s
    name = m.group("name")
    if name in ("if", "for", "while", "switch", "catch", "return", "new", "throw", "elif", "match", "with", "print", "println", "assert"):
        return False
    before = s[:m.start("name")]
    if "=" in before and "=>" not in s and not re.search(r"\b(?:function|fn|func|def)\b", s):
        return False
    return True


def match_paren(text, start):
    """Index of the `)` matching the `(` at start, or -1."""
    depth = 0
    for i in range(start, len(text)):
        c = text[i]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return i
    return -1


def parameter_count(lines, idx, language):
    """Parameters on the signature starting at lines[idx], joining continuation lines."""
    text = strip_literals(lines[idx])
    j = idx + 1
    while text.count("(") > text.count(")") and j < len(lines) and j < idx + 12:
        text += " " + strip_literals(lines[j])
        j += 1
    if language == "go":
        m = re.match(r"^\s*func\s*\(", text)
        if m:
            close = match_paren(text, m.end() - 1)
            text = text[close + 1:] if close > 0 else text
    m = SIGNATURE.search(text) if language not in INDENT_LANGUAGES else re.search(r"def\s+\w+\s*\(", text)
    if not m:
        return 0
    open_at = text.index("(", m.start())
    close = match_paren(text, open_at)
    inner = text[open_at + 1:close] if close > 0 else text[open_at + 1:]
    parts, depth, buf = [], 0, ""
    for c in inner:
        if c in "([{<":
            depth += 1
        elif c in ")]}>":
            depth -= 1
        if c == "," and depth == 0:
            parts.append(buf)
            buf = ""
        else:
            buf += c
    parts.append(buf)
    params = [p.strip() for p in parts if p.strip() and p.strip() not in ("self", "cls", "&self", "&mut self", "mut self", "*", "/")]
    params = [p for p in params if not re.match(r"^this\s*:", p)]
    return len(params)


def brace_depth_delta(line):
    s = strip_literals(line)
    return s.count("{") - s.count("}")


def routines_brace(lines):
    """(start, end, body_start) for each routine in a brace language, by brace matching."""
    out = []
    n = len(lines)
    i = 0
    while i < n:
        if is_signature(lines[i], "generic"):
            # find the body's opening brace at or after the signature line
            j, depth, body_start, opened = i, 0, None, False
            while j < n and j < i + 12:
                s = strip_literals(lines[j])
                for c in s:
                    if c == "{":
                        depth += 1
                        if not opened:
                            opened, body_start = True, j
                    elif c == "}":
                        depth -= 1
                if opened and depth <= 0:
                    break
                j += 1
            if not opened:
                i += 1
                continue
            end = j
            while end < n and depth > 0:
                end += 1
                if end < n:
                    depth += brace_depth_delta(lines[end])
            out.append((i, min(end, n - 1), body_start))
            i += 1
            continue
        i += 1
    return out


def indent_of(line):
    return len(line) - len(line.lstrip(" \t"))


def routines_indent(lines):
    """(start, end, body_start) for each routine in an indentation language."""
    out = []
    for i, line in enumerate(lines):
        if not is_signature(line, "python"):
            continue
        base = indent_of(line)
        end, j = i, i + 1
        while j < len(lines):
            l = lines[j]
            if l.strip() == "":
                j += 1
                continue
            if indent_of(l) <= base:
                break
            end = j
            j += 1
        out.append((i, end, i + 1))
    return out


def routines_of(lines, language):
    if language in INDENT_LANGUAGES:
        return routines_indent(lines)
    if language in BRACE_LANGUAGES:
        return routines_brace(lines)
    return []


def depth_at(lines, routine, idx, language):
    start, end, body_start = routine
    if language in INDENT_LANGUAGES:
        unit = None
        for j in range(body_start, min(end + 1, len(lines))):
            if lines[j].strip():
                unit = indent_of(lines[j]) - indent_of(lines[start])
                break
        if not unit or unit <= 0:
            return 0
        return max(0, (indent_of(lines[idx]) - indent_of(lines[start])) // unit - 1)
    depth = 0
    for j in range(body_start, idx):
        depth += brace_depth_delta(lines[j])
    # the routine's own body brace is one level; the line's own opening brace is not yet inside
    return max(0, depth - 1 + (1 if strip_literals(lines[idx]).lstrip().startswith("}") else 0) - (1 if strip_literals(lines[idx]).lstrip().startswith("}") else 0))


def hunk_signals(file_lines, hunk, language, kind):
    """The per-hunk structural signals, from the hunk's added lines and the file at HEAD."""
    sig = {}
    added = hunk["lines"]
    texts = [l["text"] for l in added]
    routines = routines_of(file_lines, language) if file_lines else []
    by_line = {}
    for r in routines:
        for j in range(r[0], r[1] + 1):
            by_line.setdefault(j, r)
    longest, deepest, params = 0, 0, 0
    for l in added:
        idx = l["no"] - 1
        r = by_line.get(idx)
        if r:
            longest = max(longest, r[1] - r[0] + 1)
            if idx > r[2] or (language in INDENT_LANGUAGES and idx >= r[2]):
                deepest = max(deepest, depth_at(file_lines, r, idx, language))
        if file_lines and idx < len(file_lines) and is_signature(file_lines[idx], language if language in INDENT_LANGUAGES else language):
            params = max(params, parameter_count(file_lines, idx, language))
        elif not file_lines and is_signature(l["text"], language):
            params = max(params, parameter_count(texts, added.index(l), language))
    if longest > THRESHOLDS["long_routine"]:
        sig["long_routine"] = longest
    if deepest >= THRESHOLDS["deep_nesting"]:
        sig["deep_nesting"] = deepest
    if params >= THRESHOLDS["many_parameters"]:
        sig["many_parameters"] = params
    bools = sum(1 for t in texts if BOOL_ARG.search(strip_literals(t)) and not BOOL_ARG_EXCLUDE.match(t))
    if bools:
        sig["boolean_argument"] = bools
    empties = count_empty_handlers(texts)
    if empties:
        sig["empty_handler"] = empties
    if kind != "test":
        magic = 0
        for t in texts:
            if COMMENT_START.match(t) or CONST_DECL.match(t):
                continue
            s = strip_literals(t)
            for m in MAGIC_NUMBER.finditer(s):
                lit = m.group(0).rstrip("fFdDlLuU").replace("_", "")
                if lit not in MAGIC_ALLOWED and not re.match(r"^-?\d+(?:\.\d+)?[a-z]{1,3}$", m.group(0)):
                    magic += 1
        if magic:
            sig["magic_number"] = magic
    runs = commented_out_runs(texts)
    if runs:
        sig["commented_out_code"] = runs
    todos = sum(1 for t in texts if TODO.search(t) and re.search(r"//|#|/\*|\*|--|<!--", t) and (
        COMMENT_START.match(t) or re.search(r"(?://|#|/\*|--).*\b(?:TODO|FIXME|HACK|XXX)\b", t)))
    if todos:
        sig["todo_marker"] = todos
    return sig


def count_empty_handlers(texts):
    n = 0
    for i, t in enumerate(texts):
        s = strip_literals(t) if not t.lstrip().startswith(("#", "//")) else ""
        if EMPTY_HANDLER_ONE_LINE.search(s):
            n += 1
            continue
        if EMPTY_HANDLER_OPEN.search(s):
            nxt = texts[i + 1] if i + 1 < len(texts) else ""
            if EMPTY_HANDLER_BODY.match(nxt):
                # a body of `return` alone counts; a `return value` or a call does not
                n += 1
    return n


def commented_out_runs(texts):
    runs, run = 0, 0
    for t in texts:
        if COMMENT_START.match(t):
            body = re.sub(r"^\s*(?://|#|\*|/\*|--|<!--)\s?", "", t)
            if body.strip() and STATEMENT_SYNTAX.search(body) and not TODO.search(body):
                run += 1
                continue
        if run >= 2:
            runs += 1
        run = 0
    if run >= 2:
        runs += 1
    return runs


def duplicate_blocks(files):
    """Per file, the number of 6-line windows of its added lines that occur twice among
    the diff's added lines (whitespace-normalized, blank and brace-only lines dropped)."""
    windows, per_file = {}, {f["path"]: [] for f in files}
    for f in files:
        for h in f["hunks"]:
            norm = [re.sub(r"\s+", " ", l["text"]).strip() for l in h["lines"]]
            norm = [x for x in norm if x and x not in ("{", "}", "};", "})", "end", "pass")]
            for i in range(0, len(norm) - DUPLICATE_WINDOW + 1):
                key = "\n".join(norm[i:i + DUPLICATE_WINDOW])
                windows.setdefault(key, []).append(f["path"])
                per_file[f["path"]].append(key)
    out = {}
    for path, keys in per_file.items():
        out[path] = sum(1 for k in set(keys) if len(windows[k]) >= 2)
    return out


# ---- config, cards, jobs, slices, candidates -----------------------------------------------------
def parse_config(text):
    """Return (frontmatter dict, body) of config.md; a malformed file yields ({}, text)."""
    m = re.match(r"---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        return {}, text
    fm = {}
    for line in m.group(1).split("\n"):
        km = re.match(r"^([\w-]+):\s*(.*)$", line)
        if km:
            v = km.group(2).strip()
            if len(v) >= 2 and v[0] == v[-1] and v[0] in "'\"":
                v = v[1:-1]
            fm[km.group(1)] = v
    return fm, m.group(2)


def parse_modules(fm):
    """`modules: [{name, paths: [..]}]` in the config frontmatter; JSON-shaped or absent."""
    raw = fm.get("modules")
    if not raw:
        return []
    try:
        mods = json.loads(raw)
    except ValueError:
        return []
    out = []
    for m in mods if isinstance(mods, list) else []:
        if isinstance(m, dict) and m.get("name") and isinstance(m.get("paths"), list):
            out.append({"name": str(m["name"]), "paths": [str(p).rstrip("/") for p in m["paths"]]})
    return out


INVARIANT = re.compile(r"^\s*(\d+)\.\s+\*\*(.+?)\*\*\s*:\s*(.*)$")


def parse_invariants(body):
    """Numbered invariants `N. **Title**: rule. Violation: consequence.` → PROJ-N cards."""
    cards, cur = [], None
    for line in body.split("\n"):
        im = INVARIANT.match(line)
        if im:
            cur = {"n": int(im.group(1)), "title": im.group(2).strip(), "text": im.group(3).strip()}
            cards.append(cur)
            continue
        if cur is not None and line.strip() and not line.startswith("#") and re.match(r"^\s+\S", line):
            cur["text"] += " " + line.strip()
            continue
        cur = None
    out = []
    for c in cards:
        text = c["text"]
        vm = re.search(r"\bViolation\s*:\s*(.*)$", text)
        rule = text[:vm.start()].strip() if vm else text.strip()
        violation = vm.group(1).strip() if vm else ""
        numbers = [s.strip() for s in re.split(r"(?<=[.;])\s+", text) if re.search(r"\d", s)]
        out.append({"rule_id": f"PROJ-{c['n']}", "title": c["title"], "thesis": rule,
                    "validator": violation or f"The diff shows the forbidden state of: {rule}",
                    "rationale": " ".join(numbers) if numbers else ""})
    return out


FILE_SIGNALS = ("test_file", "added_file", "duplicate_block")


def hunk_matches(card, f, h):
    """Which of the card's triggers select this hunk: (patterns, signals)."""
    pats, sigs = [], []
    if not card["triggers"]:
        return ["*"], []
    for t in card["triggers"]:
        if is_signal(t):
            name = signal_name(t)
            if name in FILE_SIGNALS:
                if f["signals"].get(name):
                    sigs.append(name)
            elif h["signals"].get(name):
                sigs.append(name)
        else:
            rx = card["_compiled"][t]
            if any(rx.search(ln["text"]) for ln in h["lines"]):
                pats.append(t)
    return pats, sigs


def build_jobs(cards, files, modules, max_job_lines, max_jobs, log):
    """One job per (card x slice). A job names its card by rule_id and each file's
    matching hunks by their index in the inventory record, so no hunk text repeats."""
    jobs = []
    by_id = {c["rule_id"]: c for c in cards}
    for card in cards:
        card["_compiled"] = {t: re.compile(t) for t in card["triggers"] if not is_signal(t)}
        slice_files = []
        for f in files:
            idx, pats, sigs = [], set(), set()
            for i, h in enumerate(f["hunks"]):
                p, s = hunk_matches(card, f, h)
                if p or s:
                    idx.append(i)
                    pats.update(p)
                    sigs.update(s)
            if idx:
                slice_files.append({"path": f["path"], "group": f["group"], "hunks": idx,
                                    "added_lines": sum(len(f["hunks"][i]["lines"]) for i in idx),
                                    "matched": {"patterns": sorted(p for p in pats if p != "*"), "signals": sorted(sigs)}})
        if not slice_files:
            continue
        total = sum(sf["added_lines"] for sf in slice_files)
        if total <= max_job_lines:
            jobs.append(make_job(card["rule_id"], "all", slice_files))
            continue
        groups = {}
        for sf in slice_files:
            groups.setdefault(sf["group"], []).append(sf)
        log(f"{card['rule_id']}: {total} matching added lines exceed {max_job_lines}; split into {len(groups)} job(s) by {'module' if modules else 'directory'}")
        for name, sfs in sorted(groups.items()):
            jobs.append(make_job(card["rule_id"], name, sfs))
    while len(jobs) > max_jobs:
        per_card = {}
        for j in jobs:
            per_card.setdefault(j["rule_id"], []).append(j)
        multi = sorted((v for v in per_card.values() if len(v) > 1), key=len, reverse=True)
        if multi:
            group = multi[0]
            merged_files = [sf for j in group for sf in j["slice"]["files"]]
            jobs = [j for j in jobs if j not in group] + [make_job(group[0]["rule_id"], "all", merged_files)]
            log(f"cap {max_jobs}: merged {len(group)} jobs of {group[0]['rule_id']} back into one")
            continue
        dropped = False
        for sev in ("suggestion", "minor"):
            cands = sorted((j for j in jobs if by_id[j["rule_id"]]["severity_default"] == sev), key=lambda j: j["slice"]["added_lines"])
            if cands:
                jobs.remove(cands[0])
                log(f"cap {max_jobs}: dropped job {cands[0]['id']} ({sev}, {cands[0]['slice']['added_lines']} lines)")
                dropped = True
                break
        if not dropped:
            log(f"cap {max_jobs}: exceeded by {len(jobs) - max_jobs} with no droppable job left; all {len(jobs)} kept")
            break
    return jobs


def make_job(rule_id, name, slice_files):
    return {"id": f"{rule_id}:{name}", "rule_id": rule_id,
            "slice": {"name": name,
                      "files": [{"path": sf["path"], "hunks": sf["hunks"], "added_lines": sf["added_lines"], "matched": sf["matched"]} for sf in slice_files],
                      "added_lines": sum(sf["added_lines"] for sf in slice_files)}}


def common_prefix(paths):
    segs = [p.split("/")[:-1] for p in paths]
    if not segs:
        return []
    prefix = segs[0]
    for s in segs[1:]:
        i = 0
        while i < min(len(prefix), len(s)) and prefix[i] == s[i]:
            i += 1
        prefix = prefix[:i]
    return prefix


def assign_groups(files, modules):
    """Group key per file: the config module whose path prefix matches, else the directory
    one segment below the common root of all changed files (at least two segments, so a
    bare `src` never names a group); test files group apart."""
    prefix = common_prefix([f["path"] for f in files])
    for f in files:
        f["group"] = None
        for m in modules:
            if any(f["path"] == p or f["path"].startswith(p + "/") for p in m["paths"]):
                f["group"] = m["name"]
                break
        if f["group"] is None:
            segs = f["path"].split("/")[:-1]
            # the directory one segment below the common root, at least two segments long
            f["group"] = "/".join(segs[:max(len(prefix) + 1, 2)]) or "(root)"
        if f["kind"] == "test":
            f["group"] = f"tests:{f['group']}"


def build_slices(files, log):
    """Three to eight file groups for the logic pass; fewer than three files → one per file."""
    if len(files) < MIN_SLICES:
        return [{"name": os.path.basename(f["path"]), "languages": [f["language"]], "files": [f["path"]],
                 "added_lines": f["added_lines"]} for f in files]
    groups = {}
    for f in files:
        groups.setdefault(f["group"], []).append(f)
    slices = [{"name": k, "files": v} for k, v in sorted(groups.items())]
    while len(slices) > MAX_SLICES:
        slices.sort(key=lambda s: len(s["files"]))
        a, b = slices[0], slices[1]
        merged = {"name": f"{a['name']}+{b['name']}", "files": a["files"] + b["files"]}
        slices = [merged] + slices[2:]
        log(f"slices: merged {a['name']} and {b['name']} to stay within {MAX_SLICES}")
    while len(slices) < MIN_SLICES:
        slices.sort(key=lambda s: len(s["files"]), reverse=True)
        big = slices[0]
        if len(big["files"]) < 2:
            break
        root = common_prefix([f["path"] for f in big["files"]])
        sub = {}
        for f in big["files"]:
            rest = f["path"].split("/")[len(root):-1]
            key = f"{big['name']}/{rest[0]}" if rest else f"{big['name']}/(root)"
            sub.setdefault(key, []).append(f)
        if len(sub) < 2:
            half = len(big["files"]) // 2
            sub = {f"{big['name']}/1": big["files"][:half], f"{big['name']}/2": big["files"][half:]}
        slices = slices[1:] + [{"name": k, "files": v} for k, v in sorted(sub.items())]
        log(f"slices: split {big['name']} into {len(sub)} to reach {MIN_SLICES}")
    out = []
    for s in sorted(slices, key=lambda s: s["name"]):
        out.append({"name": s["name"], "languages": sorted({f["language"] for f in s["files"]}),
                    "files": [f["path"] for f in s["files"]],
                    "added_lines": sum(f["added_lines"] for f in s["files"])})
    return out


# Mechanical hits the pre-pass names outright; `rule_id` names the card that owns the
# pattern once one exists, and a hit stays a candidate either way. Filled from the corpus
# by CANDIDATE_RULE_IDS; an empty value means the logic pass confirms or drops the hit.
CANDIDATE_RULE_IDS = {"empty-handler": "", "boolean-argument": "", "commented-out-code": "", "todo-marker": "",
                      "null-for-collection": "", "print-in-production": ""}
COLLECTION_SIG = re.compile(r"(?:List|Set|Map|Collection|Iterable|Array|\[\]|Vec<|HashMap<|HashSet<|Sequence|Dict\[|list\[|set\[|dict\[|\w+\[\]|Iterator)")
RETURN_NULL = re.compile(r"^\s*return\s+(?:null|None|nil|undefined)\s*;?\s*$")
PRINT_CALL = re.compile(r"\b(?:System\.out\.print|System\.err\.print|console\.log|console\.error|fmt\.Print|println!|print!|eprintln!|print\()")


def find_candidates(files, head_lines_by_path):
    out = []
    for f in files:
        lines = head_lines_by_path.get(f["path"]) or []
        routines = routines_of(lines, f["language"]) if lines else []
        for h in f["hunks"]:
            texts = [l["text"] for l in h["lines"]]
            for i, ln in enumerate(h["lines"]):
                t = ln["text"]
                s = strip_literals(t)
                if EMPTY_HANDLER_ONE_LINE.search(s) or (EMPTY_HANDLER_OPEN.search(s) and i + 1 < len(texts) and EMPTY_HANDLER_BODY.match(texts[i + 1])):
                    out.append(cand("empty-handler", f, ln))
                if BOOL_ARG.search(s) and not BOOL_ARG_EXCLUDE.match(t):
                    out.append(cand("boolean-argument", f, ln))
                if TODO.search(t) and (COMMENT_START.match(t) or re.search(r"(?://|#|/\*|--).*\b(?:TODO|FIXME|HACK|XXX)\b", t)):
                    out.append(cand("todo-marker", f, ln))
                if RETURN_NULL.match(t) and lines:
                    idx = ln["no"] - 1
                    r = next((r for r in routines if r[0] <= idx <= r[1]), None)
                    if r and COLLECTION_SIG.search(" ".join(lines[r[0]:min(r[0] + 3, len(lines))])):
                        out.append(cand("null-for-collection", f, ln))
                if f["kind"] != "test" and PRINT_CALL.search(s) and not re.search(r"\bmain\b", " ".join(lines[max(0, ln['no'] - 15):ln['no']]) if lines else ""):
                    out.append(cand("print-in-production", f, ln))
            run = 0
            for i, t in enumerate(texts):
                body = re.sub(r"^\s*(?://|#|\*|/\*|--|<!--)\s?", "", t) if COMMENT_START.match(t) else ""
                if body.strip() and STATEMENT_SYNTAX.search(body) and not TODO.search(body):
                    run += 1
                    continue
                if run >= 2:
                    out.append(cand("commented-out-code", f, h["lines"][i - run]))
                run = 0
            if run >= 2:
                out.append(cand("commented-out-code", f, h["lines"][len(texts) - run]))
    return out


def cand(cid, f, ln):
    return {"id": cid, "rule_id": CANDIDATE_RULE_IDS.get(cid) or None, "file": f["path"], "line": ln["no"],
            "text": ln["text"].strip(), "status": "needs_verification"}


def load_cards(cards_dir, log):
    cards = []
    for name in sorted(os.listdir(cards_dir)):
        if not name.endswith(".md"):
            continue
        rec, err = read_card(os.path.join(cards_dir, name))
        if err:
            log(f"card {name} skipped: {err}")
            continue
        rec["path"] = os.path.abspath(rec["path"])
        cards.append(rec)
    return cards


def size_class(n):
    if n == 0:
        return None
    if n <= SIZE_SMALL_MAX:
        return "SMALL"
    if n <= SIZE_MEDIUM_MAX:
        return "MEDIUM"
    return "LARGE"


def parse_args(argv):
    opts = {"diff_ref": None, "cards_dir": None, "path_filter": "", "repo": ".", "out_dir": "craft",
            "max_job_lines": 400, "max_jobs": 96, "config": DEFAULT_CONFIG}
    i = 0
    while i < len(argv):
        a = argv[i]
        if a.startswith("--") and i + 1 < len(argv):
            key = a[2:].replace("-", "_")
            if key not in opts:
                die(f"unknown option {a}")
            val = argv[i + 1]
            opts[key] = int(val) if key in ("max_job_lines", "max_jobs") else val
            i += 2
            continue
        die(f"unexpected argument {a!r}")
    if not opts["cards_dir"]:
        die("--cards-dir is required")
    return opts


def build_plan(opts, log):
    repo = os.path.abspath(opts["repo"])
    if git(repo, "rev-parse", "--is-inside-work-tree").strip() != "true":
        die("not a git working tree")
    if opts["diff_ref"]:
        mode = "committed"
        base_sha, head_sha = resolve_refs(repo, opts["diff_ref"])
        args = ["diff", "-U0", "--no-color", "--no-ext-diff", base_sha, head_sha, "--"]
        if opts["path_filter"]:
            args.append(opts["path_filter"])
        files = parse_diff(git(repo, *args))
    else:
        mode = "worktree"
        base_sha = git(repo, "rev-parse", "HEAD").strip()
        head_sha = "worktree"
        args = ["diff", "-U0", "--no-color", "--no-ext-diff", "HEAD", "--"]
        if opts["path_filter"]:
            args.append(opts["path_filter"])
        files = parse_diff(git(repo, *args)) + untracked_records(repo, opts["path_filter"])
    kept, skipped, head_lines = [], [], {}
    for f in files:
        if f["binary"]:
            skipped.append({"path": f["path"], "reason": "binary"})
            continue
        text = head_text(repo, mode, head_sha, f["path"])
        reason = deny_reason(f["path"], text)
        if reason:
            skipped.append({"path": f["path"], "reason": reason})
            continue
        f["language"] = language_of(f["path"])
        f["kind"] = kind_of(f["path"], f["language"])
        head_lines[f["path"]] = text.split("\n") if text is not None else None
        kept.append(f)
    for s in skipped:
        log(f"skipped {s['path']}: {s['reason']}")
    files = kept
    dup = duplicate_blocks(files)
    for f in files:
        f["signals"] = {"test_file": f["kind"] == "test", "added_file": f["status"] == "added", "duplicate_block": dup.get(f["path"], 0)}
        for h in f["hunks"]:
            h["signals"] = hunk_signals(head_lines.get(f["path"]), h, f["language"], f["kind"])
    config_path = os.path.join(repo, opts["config"])
    config, body, invariants, modules = None, "", [], []
    if os.path.isfile(config_path):
        with open(config_path, encoding="utf-8") as handle:
            config, body = parse_config(handle.read())
        invariants = parse_invariants(body)
        modules = parse_modules(config)
    config_rel = os.path.relpath(config_path, repo).replace(os.sep, "/")
    config_changed = any(f["path"] == config_rel for f in files) or config_rel in [s["path"] for s in skipped]
    assign_groups(files, modules)
    cards = load_cards(opts["cards_dir"], log)
    project_dir = os.path.join(repo, PROJECT_CARDS_DIR)
    card_paths = []
    if os.path.isdir(project_dir):
        for name in sorted(os.listdir(project_dir)):
            if name.endswith(".md"):
                p = os.path.join(project_dir, name)
                rec, err = read_card(p)
                if err:
                    log(f"project card {name} skipped: {err}")
                    continue
                rec["path"] = os.path.abspath(p)
                cards.append(rec)
                card_paths.append(os.path.relpath(p, repo).replace(os.sep, "/"))
    jobs = build_jobs(cards, files, modules, opts["max_job_lines"], opts["max_jobs"], log) if files else []
    slices = build_slices(files, log) if files else []
    candidates = find_candidates(files, head_lines)
    dispatched = {j["rule_id"] for j in jobs} | {c["rule_id"] for c in candidates if c.get("rule_id")}
    languages = {}
    for f in files:
        languages[f["language"]] = languages.get(f["language"], 0) + 1
    plan = {
        "inventory": {
            "mode": mode, "diff_ref": f"{base_sha}...{head_sha}", "base_sha": base_sha, "head_sha": head_sha,
            "path_filter": opts["path_filter"], "size_class": size_class(len(files)), "file_count": len(files),
            "languages": languages,
            "files": [{"path": f["path"], "language": f["language"], "kind": f["kind"], "status": f["status"], "group": f["group"],
                       "hunks": f["hunks"], "signals": f["signals"], "added_lines": f["added_lines"], "removed_lines": f["removed_lines"]}
                      for f in files],
            "skipped": skipped,
            "config_path": config_rel if config is not None else None,
            "config_changed": config_changed,
            "config": config,
        },
        "cards": [{k: v for k, v in c.items() if not k.startswith("_")} for c in cards if c["rule_id"] in dispatched],
        "jobs": jobs,
        "slices": slices,
        "candidates": candidates,
        "project_cards": {"cards": invariants, "card_paths": card_paths},
    }
    if not files:
        log("No reviewable changes in this scope")
    signal_counts = {}
    for f in files:
        for h in f["hunks"]:
            for k in h["signals"]:
                signal_counts[k] = signal_counts.get(k, 0) + 1
    log(f"{len(files)} file(s), size {plan['inventory']['size_class']}, mode {mode}, languages {languages}, "
        f"{len(cards)} card(s), {len(jobs)} job(s), {len(slices)} slice(s), {len(candidates)} candidate(s), "
        f"signals {signal_counts or 'none'}")
    return plan


def main(argv):
    opts = parse_args(argv)
    log = Log()
    plan = build_plan(opts, log)
    out_dir = os.path.join(os.path.abspath(opts["repo"]), opts["out_dir"])
    os.makedirs(out_dir, exist_ok=True)
    with open(os.path.join(out_dir, "plan.json"), "w", encoding="utf-8") as handle:
        json.dump(plan, handle, indent=1)
    with open(os.path.join(out_dir, "plan.log"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(log.lines) + "\n")
    print("\n".join(log.lines))
    return 2 if not plan["inventory"]["files"] else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
